<?php
// Database access: one shared mysqli connection and small prepared statement helpers.

// Returns the shared connection, opening it on first use.
function db(): mysqli
{
    static $conn = null;
    if ($conn === null) {
        mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
        $conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
        $conn->set_charset('utf8mb4');
        $conn->query("SET time_zone = '+08:00'");
    }
    return $conn;
}

// Runs a prepared statement with positional parameters and returns the statement.
function db_run(string $sql, array $params = []): mysqli_stmt
{
    $stmt = db()->prepare($sql);
    $stmt->execute($params ? array_values($params) : null);
    return $stmt;
}

// Returns all rows of a query as associative arrays.
function db_all(string $sql, array $params = []): array
{
    return db_run($sql, $params)->get_result()->fetch_all(MYSQLI_ASSOC);
}

// Returns the first row of a query, or null.
function db_one(string $sql, array $params = []): ?array
{
    $row = db_run($sql, $params)->get_result()->fetch_assoc();
    return $row ?: null;
}

// Returns the first column of the first row, or null.
function db_value(string $sql, array $params = []): mixed
{
    $row = db_run($sql, $params)->get_result()->fetch_row();
    return $row ? $row[0] : null;
}

// Runs an INSERT, UPDATE or DELETE and returns the number of affected rows.
function db_exec(string $sql, array $params = []): int
{
    return db_run($sql, $params)->affected_rows;
}

// Returns the id generated by the last INSERT.
function db_insert_id(): int
{
    return (int) db()->insert_id;
}
