<?php
// The BookNest catalogue, used by tools/build-seed.php.
//
// Modern books: titles, authors, publishers, years, page counts and ISBNs are real and were
// checked against Open Library (openlibrary.org) on 1 October 2026. Prices are BookNest's own
// shelf prices in Singapore dollars, set close to what Singapore bookshops charge.
// Every hook, synopsis, idea and "who it is for" line below is written by the BookNest team.
// Nothing is copied from the books or from publisher blurbs, because the books are in copyright.
//
// Classics: public domain works. Their reader samples are real opening pages from Project Gutenberg.

$categories = [
    ['Self Improvement', 'self-improvement', 'Small changes, better habits and clearer thinking.'],
    ['Business and Money', 'business-money', 'How money, companies and good decisions really work.'],
    ['Fiction', 'fiction', 'Novels people are pressing into their friends\' hands.'],
    ['Mystery and Thriller', 'mystery-thriller', 'Twists you will not see coming, and a few you will.'],
    ['Sci-Fi and Fantasy', 'sci-fi-fantasy', 'Other worlds, impossible problems and dragons.'],
    ['Non Fiction', 'non-fiction', 'True stories, science and history worth your evening.'],
    ['Classics', 'classics', 'Out of copyright and never out of print. Read the real opening pages.'],
];

// Builds one modern book entry.
function book(string $isbn, string $title, string $author, string $cat, string $publisher, string $format, int $year,
              int $pages, float $price, float $rating, int $stock, int $days, string $hook, string $synopsis,
              array $ideas, string $audience, int $staff = 0, int $featured = 0): array
{
    return compact('isbn', 'title', 'author', 'cat', 'publisher', 'format', 'year', 'pages', 'price', 'rating',
        'stock', 'days', 'hook', 'synopsis', 'ideas', 'audience', 'staff', 'featured');
}

$modern = [
    // ---- Self Improvement ---------------------------------------------------------------------
    book('9780735211292', 'Atomic Habits', 'James Clear', 'self-improvement', 'Avery', 'Hardcover', 2018, 320, 39.90, 4.4, 24, 30,
        'Get one percent better every day, and let the maths do the rest.',
        'James Clear argues that lasting change does not come from big resolutions but from tiny habits repeated daily. He explains how habits form, why good ones fade and bad ones stick, and offers a practical system for building routines that fit the person you want to become.',
        ['Small improvements compound. Getting slightly better each day adds up to a very different year.',
         'Focus on systems, not goals. Winners and losers often share the same goals; what differs is the daily process.',
         'Make good habits obvious, attractive, easy and satisfying, and do the reverse for the habits you want to drop.'],
        'For anyone who has set the same resolution twice and wants a method that survives a bad week.', 1, 1),
    book('9780062457714', 'The Subtle Art of Not Giving a F*ck', 'Mark Manson', 'self-improvement', 'HarperOne', 'Hardcover', 2016, 224, 34.90, 3.9, 14, 70,
        'A blunt, funny argument for caring about fewer things, and caring about them properly.',
        'Mark Manson pushes back against relentless positivity. His point is that our attention is limited, problems never disappear, and a good life comes from choosing which struggles are worth it. Sweary, direct and more thoughtful than the title suggests.',
        ['You only have so much care to give, so spend it on what matches your values.',
         'Happiness comes from solving problems, not from avoiding them.',
         'Taking responsibility for your reactions is different from taking the blame for what happened.'],
        'For readers tired of cheerful self help who want honesty with a sense of humour.'),
    book('9781455586691', 'Deep Work', 'Cal Newport', 'self-improvement', 'Grand Central Publishing', 'Hardcover', 2016, 295, 36.90, 4.2, 11, 95,
        'The ability to focus without distraction is becoming rare, which makes it valuable.',
        'Computer science professor Cal Newport makes the case that long stretches of undistracted concentration produce the work that matters most. The first half explains why; the second gives rules for protecting focus in a world of notifications, meetings and open plan offices.',
        ['Deep work produces results that are hard to copy; shallow work mostly keeps you busy.',
         'Attention is trained like a muscle, and constant switching weakens it.',
         'Schedule focus on purpose: fixed hours, clear rituals and a firm end to the working day.'],
        'For students and knowledge workers who end busy days unsure what they actually finished.', 1),
    book('9780143130727', 'Ikigai', 'Héctor García and Francesc Miralles', 'self-improvement', 'Penguin Life', 'Hardcover', 2017, 194, 27.90, 3.8, 16, 120,
        'What the long lived people of Okinawa can teach us about a reason to get up in the morning.',
        'Two writers visit Ogimi, a Japanese village famous for its centenarians, and ask what keeps people active and content into old age. They find purpose, friendship, gentle movement, modest meals and work that never quite stops. A short, calm, illustrated read.',
        ['Ikigai is the overlap of what you love, what you are good at, what the world needs and what you can be paid for.',
         'Staying lightly busy matters more than retiring; many of the villagers never fully stop working.',
         'Small daily rituals, close friends and eating until you are almost full add up over decades.'],
        'For anyone wanting a gentle, quick read about purpose rather than a programme to follow.'),
    book('9781982137274', 'The 7 Habits of Highly Effective People', 'Stephen R. Covey', 'self-improvement', 'Simon & Schuster', 'Paperback', 1989, 432, 29.90, 4.2, 9, 150,
        'The classic framework for running your life on principles instead of urgency.',
        'First published in 1989 and revised for its thirtieth anniversary, Covey\'s book sets out seven habits that move a person from dependence to independence to working well with others. It asks readers to start with character, not techniques.',
        ['Be proactive: act on what you can influence instead of reacting to what you cannot.',
         'Begin with the end in mind, then put first things first by scheduling what is important before what is urgent.',
         'Seek first to understand, then to be understood; real listening comes before persuading.'],
        'For readers who want one thorough, structured book on personal effectiveness rather than many short ones.'),
    book('9781472139955', 'Mindset', 'Carol S. Dweck', 'self-improvement', 'Robinson', 'Paperback', 2006, 320, 22.90, 4.1, 13, 8,
        'Why believing you can improve changes how much you actually do.',
        'Stanford psychologist Carol Dweck summarises decades of research into two beliefs about ability. People with a fixed mindset see talent as set; people with a growth mindset see it as something built through effort. The difference shapes school, sport, work and relationships.',
        ['A fixed mindset treats failure as a verdict; a growth mindset treats it as information.',
         'Praising effort and strategy helps children more than praising intelligence.',
         'Mindsets are not permanent traits. They can be noticed, and changed, in specific situations.'],
        'For students, parents, teachers and coaches, and anyone who avoids things they might be bad at.'),

    // ---- Business and Money --------------------------------------------------------------------
    book('9780857197689', 'The Psychology of Money', 'Morgan Housel', 'business-money', 'Harriman House', 'Paperback', 2020, 250, 24.90, 4.3, 21, 2,
        'Doing well with money has little to do with how clever you are, and a lot to do with how you behave.',
        'In nineteen short chapters, Morgan Housel shows that financial outcomes are driven less by spreadsheets than by ego, fear, patience and luck. Stories replace formulas, and the advice is modest: save, stay in the game, and know what is enough.',
        ['Wealth is what you do not see: the money not spent on looking rich.',
         'Compounding rewards time more than brilliance, so the first job is simply to avoid being wiped out.',
         'Everyone\'s view of money is shaped by their own slice of history, which is why reasonable people disagree.'],
        'For first time savers and investors who want principles they will still agree with in twenty years.', 1),
    book('9781612680194', 'Rich Dad Poor Dad', 'Robert T. Kiyosaki', 'business-money', 'Plata Publishing', 'Paperback', 1997, 301, 16.90, 4.1, 26, 140,
        'Two fathers, two attitudes to money, and one of the best selling finance books ever.',
        'Kiyosaki contrasts the advice of his own educated but struggling father with that of his friend\'s entrepreneurial father. The book popularised a simple distinction between assets that put money in your pocket and liabilities that take it out.',
        ['The rich buy assets; many people buy liabilities believing they are assets.',
         'Schools teach people to work for money, but rarely how money works.',
         'Financial literacy and the willingness to learn matter more than a high salary.'],
        'For readers new to personal finance who want motivation first and detail later.'),
    book('9780374533557', 'Thinking, Fast and Slow', 'Daniel Kahneman', 'business-money', 'Farrar, Straus and Giroux', 'Paperback', 2011, 499, 27.90, 4.2, 10, 60,
        'A Nobel laureate\'s tour of the two systems in your head, and how often the fast one fools you.',
        'Daniel Kahneman describes a quick, intuitive System 1 and a slow, effortful System 2. Through decades of experiments he shows how the fast system produces confident errors in judgement, from anchoring to overconfidence, and what little can be done about it.',
        ['Most decisions are made by fast intuition, with slow reasoning stepping in less often than we think.',
         'Losses hurt roughly twice as much as equal gains please, which bends our choices.',
         'We judge by what comes to mind easily, so vivid stories beat dull statistics.'],
        'For patient readers who enjoy evidence and are willing to doubt their own judgement.', 1),
    book('9780804139298', 'Zero to One', 'Peter Thiel with Blake Masters', 'business-money', 'Crown Business', 'Hardcover', 2014, 195, 35.90, 4.2, 8, 110,
        'Copying takes the world from one to many. Creating something new takes it from zero to one.',
        'Based on a class Thiel taught at Stanford, this short book argues that the most valuable companies build something genuinely new instead of competing in crowded markets. It is opinionated, contrarian and full of questions founders should ask.',
        ['Competition erodes profit; lasting businesses find a small market they can dominate first.',
         'Ask what important truth very few people agree with you on. Good companies are built on such secrets.',
         'Start small, then expand step by step, rather than chasing a huge market from day one.'],
        'For anyone curious about startups who prefers arguments to checklists.'),
    book('9780307887894', 'The Lean Startup', 'Eric Ries', 'business-money', 'Crown Business', 'Hardcover', 2011, 336, 36.90, 4.1, 7, 90,
        'Stop guessing what customers want. Build a little, measure, and learn.',
        'Eric Ries applies lean manufacturing ideas to new ventures. Instead of long plans and big launches, he proposes small experiments, honest metrics and a willingness to change direction. The vocabulary he introduced is now standard in the industry.',
        ['A minimum viable product is the smallest thing you can build to learn something real.',
         'Vanity metrics flatter; actionable metrics tell you whether to persevere or pivot.',
         'The build, measure, learn loop should run as quickly as possible.'],
        'For founders, product teams and students working on a project nobody has asked for yet.'),
    book('9781591846444', 'Start with Why', 'Simon Sinek', 'business-money', 'Portfolio', 'Paperback', 2009, 256, 24.90, 4.1, 12, 45,
        'People do not buy what you do. They buy why you do it.',
        'Simon Sinek looks at leaders and companies that inspire loyalty and finds they communicate from the inside out: purpose first, then method, then product. He calls the pattern the Golden Circle and argues it can be learned.',
        ['The Golden Circle runs from why, to how, to what, and most organisations explain it backwards.',
         'A clear purpose attracts people who share it, which is stronger than any incentive.',
         'Success can blur the original why, so it has to be restated as an organisation grows.'],
        'For team leaders, club committees and anyone who has to persuade others to care.'),

    // ---- Fiction ------------------------------------------------------------------------------
    book('9780525559474', 'The Midnight Library', 'Matt Haig', 'fiction', 'Viking', 'Hardcover', 2020, 288, 32.90, 4.0, 18, 20,
        'Between life and death there is a library, and every book is a life you might have lived.',
        'Nora Seed, full of regrets, finds herself in a library where each volume lets her try a different version of her life. Matt Haig turns a fantastical idea into a warm, readable novel about choices, disappointment and what makes a life worth staying for.',
        ['Regret assumes the other path would have been better, and that is rarely the whole story.',
         'Small decisions ripple outward in ways nobody can predict.',
         'An ordinary life can hold more than it seems to from inside a bad day.'],
        'For readers who want a hopeful novel that takes sadness seriously.', 1),
    book('9780735219090', 'Where the Crawdads Sing', 'Delia Owens', 'fiction', 'G.P. Putnam\'s Sons', 'Hardcover', 2018, 384, 34.90, 4.4, 15, 80,
        'A girl raised by the marsh, and a death the town is sure she caused.',
        'Kya grows up alone in the wetlands of North Carolina, abandoned by her family and shunned by the nearby town. When a popular young man is found dead, suspicion falls on the Marsh Girl. Part nature writing, part coming of age story, part courtroom mystery.',
        ['Isolation shapes a person, but so does the place that shelters them.',
         'Communities are quick to blame whoever they never bothered to know.',
         'The natural world is described with a biologist\'s eye, and it is half the pleasure of the book.'],
        'For readers who like atmosphere, slow reveals and a strong sense of place.'),
    book('9780062315007', 'The Alchemist', 'Paulo Coelho', 'fiction', 'HarperOne', 'Paperback', 1988, 208, 21.90, 3.9, 22, 160,
        'A shepherd follows a dream across the desert and finds what he was not looking for.',
        'Santiago, an Andalusian shepherd boy, dreams of treasure near the Egyptian pyramids and sets out to find it. Along the way he meets a king, a crystal merchant and an alchemist. A short fable about listening to your heart, translated into more than eighty languages.',
        ['Everyone has a personal legend, and most people talk themselves out of pursuing it.',
         'The journey changes the traveller more than the treasure does.',
         'Fear of failure stops more dreams than failure itself.'],
        'For anyone at a turning point who wants a simple story to think with.'),
    book('9781984822185', 'Normal People', 'Sally Rooney', 'fiction', 'Hogarth', 'Paperback', 2018, 272, 22.90, 3.8, 12, 55,
        'Two people who cannot stay together and cannot stay apart.',
        'Connell and Marianne grow up in the same small Irish town, in very different circumstances, and move in and out of each other\'s lives through school and university. Rooney writes in spare, exact prose about class, intimacy and how much one person can alter another.',
        ['Who has power in a relationship shifts with setting, money and confidence.',
         'Much of what goes wrong between people is simply never said out loud.',
         'Being truly known by someone is both what the characters want most and fear most.'],
        'For readers who prefer close character study to plot.'),
    book('9780593321201', 'Tomorrow, and Tomorrow, and Tomorrow', 'Gabrielle Zevin', 'fiction', 'Knopf', 'Hardcover', 2022, 401, 36.90, 4.1, 10, 6,
        'Two friends, thirty years and the video games they build together.',
        'Sam and Sadie meet as children in a hospital games room and later found a game studio that makes them famous. Zevin follows their creative partnership, which is closer than friendship and never quite romance, through success, grief and rivalry.',
        ['Making something with another person is its own kind of love.',
         'Games offer what life does not: the chance to try again.',
         'Ambition and loyalty pull against each other for decades, and neither wins cleanly.'],
        'For readers who enjoy long friendships on the page; no knowledge of games is needed.', 1),
    book('9781455563920', 'Pachinko', 'Min Jin Lee', 'fiction', 'Grand Central Publishing', 'Paperback', 2017, 512, 24.90, 4.3, 9, 100,
        'Four generations of a Korean family in Japan, starting with one unplanned pregnancy.',
        'Beginning in a fishing village in Korea in the early 1900s, the novel follows Sunja and her descendants as they build lives in a Japan that never fully accepts them. A sweeping, compassionate family saga about identity, sacrifice and endurance.',
        ['History is felt most sharply in ordinary households, not in parliaments.',
         'Belonging can be withheld for generations, and people build good lives anyway.',
         'Each generation pays for, and benefits from, choices made before it was born.'],
        'For readers who like to sink into a long family story across the twentieth century.'),

    // ---- Mystery and Thriller -------------------------------------------------------------------
    book('9781250301697', 'The Silent Patient', 'Alex Michaelides', 'mystery-thriller', 'Celadon Books', 'Hardcover', 2019, 336, 35.90, 4.2, 17, 25,
        'She shot her husband five times and has not spoken a word since.',
        'Alicia Berenson, a famous painter, is found beside her husband\'s body and never speaks again. Psychotherapist Theo Faber becomes determined to get her to talk. A tightly built psychological thriller known for its final turn.',
        ['Silence can be a form of speech, and everyone in the story reads it differently.',
         'The therapist\'s own history matters as much as the patient\'s.',
         'Greek tragedy runs quietly under the plot and rewards readers who notice it.'],
        'For thriller readers who like to be fooled fairly.', 1),
    book('9780307588371', 'Gone Girl', 'Gillian Flynn', 'mystery-thriller', 'Broadway Books', 'Paperback', 2012, 422, 21.90, 4.1, 14, 130,
        'On their fifth anniversary, Amy disappears, and Nick does not look innocent.',
        'When Amy Dunne goes missing, her husband Nick becomes the obvious suspect. The story is told by both of them, in his present and her diary, and neither can be fully trusted. A dark, sharp novel about a marriage and the stories people tell.',
        ['Two narrators give two versions, and the reader has to decide how much of each to believe.',
         'Public opinion and the media shape a case as much as the evidence does.',
         'The book is as interested in what a marriage hides as in who did what.'],
        'For readers who enjoy unreliable narrators and do not need to like the characters.'),
    book('9781594634024', 'The Girl on the Train', 'Paula Hawkins', 'mystery-thriller', 'Riverhead Books', 'Paperback', 2015, 336, 22.90, 4.0, 11, 85,
        'She watches the same couple from the same train every day. Then one of them vanishes.',
        'Rachel passes the same houses on her commute and invents lives for the people she sees. When the woman she has been watching goes missing, Rachel thinks she knows something, but her memory has gaps. Told by three women whose accounts do not quite agree.',
        ['A witness who doubts her own memory is a gripping and uneasy guide.',
         'What looks like a perfect life from a train window rarely is.',
         'The three narrators slowly reveal how their stories connect.'],
        'For commuters, and anyone who likes a mystery that reads quickly.'),
    book('9781984880987', 'The Thursday Murder Club', 'Richard Osman', 'mystery-thriller', 'Penguin Books', 'Paperback', 2020, 384, 23.90, 3.9, 13, 40,
        'Four retirees meet weekly to solve old murders. Then a new one lands on their doorstep.',
        'In a peaceful retirement village, Elizabeth, Joyce, Ibrahim and Ron spend Thursdays going through unsolved cases. When a local developer is killed, they have a live investigation and skills the police underestimate. Warm, witty and properly plotted.',
        ['Being overlooked because of your age can be turned into a real advantage.',
         'Friendship late in life is at the heart of the book, alongside the puzzle.',
         'Humour and sadness sit close together, and the story lets both in.'],
        'For readers who want a clever mystery that is also good company.'),
    book('9780307474278', 'The Da Vinci Code', 'Dan Brown', 'mystery-thriller', 'Anchor', 'Paperback', 2003, 608, 15.90, 3.9, 19, 170,
        'A murder in the Louvre, a trail of codes, and a secret someone will kill to protect.',
        'Symbologist Robert Langdon is called to the Louvre, where a curator has been found dead beside a cryptic message. With cryptologist Sophie Neveu he follows clues hidden in art and architecture across Paris and London. Short chapters and constant cliffhangers.',
        ['Puzzles built from paintings, anagrams and number sequences drive the chase.',
         'The plot is fiction layered on real places, which is why people visit them with the book in hand.',
         'Nearly every chapter ends on a hook, so it is very hard to stop.'],
        'For holiday reading, long flights and anyone who loves a treasure hunt.'),
    book('9781538742570', 'The Housemaid', 'Freida McFadden', 'mystery-thriller', 'Grand Central Publishing', 'Paperback', 2022, 336, 23.90, 4.3, 16, 3,
        'A live in job with a wealthy family seems like a fresh start. The bedroom locks from the outside.',
        'Millie needs work and somewhere to live, and the Winchesters offer both. But Nina Winchester\'s behaviour grows stranger, and the attic room is not what it seemed. A fast, twisty domestic thriller that became a word of mouth hit.',
        ['The power balance inside the house keeps shifting.',
         'Everyone is hiding something, including the narrator.',
         'The second half reframes what you thought you understood in the first.'],
        'For readers who want to finish a book in two sittings.'),

    // ---- Sci-Fi and Fantasy --------------------------------------------------------------------
    book('9780593135204', 'Project Hail Mary', 'Andy Weir', 'sci-fi-fantasy', 'Ballantine Books', 'Hardcover', 2021, 496, 38.90, 4.5, 15, 15,
        'He wakes up alone on a spaceship with no memory, and the whole of humanity depending on him.',
        'A man wakes from a coma millions of kilometres from Earth, unable to remember his name or his mission. As his memory returns he realises he is the last hope of stopping a threat to the Sun. Science heavy, funny and unexpectedly moving.',
        ['Problems are solved step by step with real physics and a lot of improvisation.',
         'Cooperation with someone utterly unlike you sits at the centre of the story.',
         'Courage is shown as something people grow into, not something they start with.'],
        'For fans of The Martian and anyone who likes science explained with jokes.', 1),
    book('9780441013593', 'Dune', 'Frank Herbert', 'sci-fi-fantasy', 'Ace', 'Paperback', 1965, 544, 25.90, 4.3, 12, 125,
        'A desert planet, a precious spice, and a young heir who may be more than human.',
        'When House Atreides takes control of Arrakis, the only source of the most valuable substance in the universe, it walks into a trap. Young Paul Atreides must survive among the desert Fremen. A founding work of science fiction about politics, religion and ecology.',
        ['Control of a single resource shapes an entire empire.',
         'The desert ecology is worked out in detail and drives the plot.',
         'The book is wary of heroes and of what happens when people follow them.'],
        'For readers ready for a dense, rewarding world to get lost in.'),
    book('9780553418026', 'The Martian', 'Andy Weir', 'sci-fi-fantasy', 'Broadway Books', 'Paperback', 2011, 388, 22.90, 4.4, 14, 75,
        'Stranded on Mars with no way home, one astronaut decides to science his way out.',
        'After a storm forces his crew to leave, Mark Watney is presumed dead and left alone on Mars. With limited supplies and no contact with Earth, he has to grow food, make water and stay alive. Told mostly through his very funny log entries.',
        ['Survival is a long list of problems solved one at a time.',
         'Humour is how the narrator stays sane, and why the book is so readable.',
         'Back on Earth, rescuing one person becomes a shared international effort.'],
        'For readers who enjoy practical problem solving and a sarcastic narrator.'),
    book('9781649374042', 'Fourth Wing', 'Rebecca Yarros', 'sci-fi-fantasy', 'Red Tower Books', 'Hardcover', 2023, 517, 39.90, 4.6, 20, 5,
        'At this war college you either bond with a dragon or you die trying.',
        'Violet Sorrengail expected a quiet life among books. Instead her mother, a general, orders her into the brutal riders\' quadrant, where cadets compete for dragons and plenty do not survive. A fast paced romantic fantasy that became a publishing phenomenon.',
        ['The heroine wins through wit and stubbornness rather than strength.',
         'Rivalry, loyalty and attraction are tangled together from the first chapters.',
         'The college\'s official history is not the whole truth.'],
        'For readers who want dragons, danger and romance in one very quick read.'),
    book('9780547928227', 'The Hobbit', 'J. R. R. Tolkien', 'sci-fi-fantasy', 'Mariner Books', 'Paperback', 1937, 300, 21.90, 4.3, 18, 145,
        'A comfort loving hobbit is talked into an adventure involving dwarves, a dragon and a ring.',
        'Bilbo Baggins is perfectly happy at home until the wizard Gandalf and thirteen dwarves arrive and sweep him into a quest to reclaim treasure from the dragon Smaug. The gentler, funnier story that opens the door to Middle-earth.',
        ['An unlikely hero discovers courage he did not know he had.',
         'Cleverness and mercy matter as much as swords.',
         'Coming home is different once you have been away.'],
        'For readers of any age, and the best place to start with Tolkien.'),
    book('9781408855652', 'Harry Potter and the Philosopher\'s Stone', 'J. K. Rowling', 'sci-fi-fantasy', 'Bloomsbury', 'Paperback', 1997, 332, 18.90, 4.5, 28, 180,
        'On his eleventh birthday, an unwanted boy learns he is a wizard.',
        'Harry Potter has grown up in a cupboard under the stairs, unaware of who his parents were. A letter delivered by owl changes everything, and he begins his first year at Hogwarts School of Witchcraft and Wizardry. The book that started the series.',
        ['Friendship is what carries Harry through, more than talent.',
         'The wizarding world is revealed piece by piece, through the eyes of someone as new to it as the reader.',
         'A mystery runs through the school year and is solved by the children, not the adults.'],
        'For younger readers starting chapter books, and adults rereading for comfort.'),

    // ---- Non Fiction ----------------------------------------------------------------------------
    book('9780062316110', 'Sapiens', 'Yuval Noah Harari', 'non-fiction', 'Harper Perennial', 'Paperback', 2011, 464, 29.90, 4.4, 16, 50,
        'How an unremarkable ape came to run the planet, in under five hundred pages.',
        'Historian Yuval Noah Harari surveys seventy thousand years of human history, from the first storytellers to the present. He argues that our ability to believe in shared fictions, such as money, nations and laws, is what let strangers cooperate in large numbers.',
        ['Shared stories allow millions of strangers to work together.',
         'The agricultural revolution fed more people but arguably made individual lives harder.',
         'Money, empires and religions are presented as the forces that unified humankind.'],
        'For curious general readers who want the very big picture.', 1),
    book('9780399590504', 'Educated', 'Tara Westover', 'non-fiction', 'Random House', 'Hardcover', 2018, 352, 37.90, 4.5, 11, 65,
        'She first set foot in a classroom at seventeen. She left with a doctorate from Cambridge.',
        'Tara Westover grew up in rural Idaho in a survivalist family that distrusted schools and hospitals. Her memoir describes teaching herself enough to enter university, and the painful cost of an education that put her at odds with the people she loved.',
        ['Education is shown as the ability to see your own life from more than one viewpoint.',
         'Loyalty to family and loyalty to yourself can pull in opposite directions.',
         'Memory is uncertain, and the author is honest about where hers is contested.'],
        'For readers of memoir, and anyone who has outgrown a version of home.'),
    book('9781524763138', 'Becoming', 'Michelle Obama', 'non-fiction', 'Crown', 'Hardcover', 2018, 448, 43.90, 4.4, 8, 115,
        'From the South Side of Chicago to the White House, in her own words.',
        'Michelle Obama tells her story in three parts: growing up in a working family in Chicago, building a career and a marriage, and eight years as First Lady of the United States. Candid about doubt, ambition and the strain of public life.',
        ['Who you are is described as something always in progress, never finished.',
         'Mentors and family expectations shaped her long before politics did.',
         'She writes frankly about balancing work, children and a husband\'s career.'],
        'For readers who enjoy memoirs with warmth and detail.'),
    book('9780553380163', 'A Brief History of Time', 'Stephen Hawking', 'non-fiction', 'Bantam', 'Paperback', 1988, 212, 26.90, 4.2, 10, 155,
        'Where did the universe come from, and where is it going? A physicist explains without equations.',
        'Stephen Hawking guides general readers through space and time, the big bang, black holes and the search for a theory that unites physics. Famous for containing only one equation, it has introduced millions of people to cosmology.',
        ['Space and time form one fabric that matter bends.',
         'Black holes are not entirely black, an idea Hawking himself contributed.',
         'Physicists are still looking for one theory joining gravity with quantum mechanics.'],
        'For curious non scientists prepared to read slowly and reread a page now and then.'),
    book('9780307352156', 'Quiet', 'Susan Cain', 'non-fiction', 'Broadway Books', 'Paperback', 2012, 368, 24.90, 4.1, 13, 35,
        'A third of us are introverts, living in a world designed for people who talk first.',
        'Susan Cain examines how Western culture came to prize the outgoing personality, and what is lost when quieter people are overlooked. Drawing on psychology and many interviews, she argues for workplaces and classrooms that make room for both temperaments.',
        ['Introversion is about where you get your energy, not about shyness.',
         'Group brainstorming and open offices often produce worse ideas than time alone.',
         'Quiet leaders can do especially well with teams that take initiative.'],
        'For introverts, and for the extroverts who live, study and work with them.'),
    book('9780807014271', 'Man\'s Search for Meaning', 'Viktor E. Frankl', 'non-fiction', 'Beacon Press', 'Paperback', 1946, 165, 19.90, 4.4, 20, 10,
        'A psychiatrist\'s account of surviving the camps, and what kept people alive inside them.',
        'Viktor Frankl describes his years in Nazi concentration camps and what he observed there as a psychiatrist. In the second part he outlines logotherapy, his view that the deepest human drive is the search for meaning. Short, sober and unforgettable.',
        ['Those who held on to a purpose were more able to endure.',
         'We cannot always choose our circumstances, but we can choose our response to them.',
         'Meaning is found in work, in love and in the stance taken toward unavoidable suffering.'],
        'For anyone going through a hard time, and everyone else too.', 1),
];

// Public domain classics with real opening pages:
// [gutenberg id, start markers, title, author, year, pages, price, rating, stock, staff pick, days since added, hook, synopsis]
$classics = [
    [1342, ['It is a truth universally acknowledged, that a single man'], 'Pride and Prejudice', 'Jane Austen', 1813, 432, 12.90, 4.3, 18, 0, 64,
     'Five sisters, one proud gentleman, and a first impression that gets everything wrong.',
     'When the wealthy Mr Bingley rents Netherfield Park, the Bennet household is thrown into happy chaos. Elizabeth, the sharpest of five sisters, takes an instant dislike to his friend Mr Darcy. Austen\'s comedy of manners is funny, warm and exact about how pride and quick judgement can blind even the cleverest people.'],
    [84, ['You will rejoice to hear that no disaster'], 'Frankenstein', 'Mary Shelley', 1818, 280, 11.90, 3.9, 16, 0, 88,
     'A young scientist builds a life, then runs from it. Two hundred years later, we still argue about who the monster is.',
     'Victor Frankenstein discovers how to give life to dead matter and creates a being, then abandons it in horror. Alone and rejected, the creature learns to speak, read and feel, and demands to know why he was made. Shelley\'s novel invented science fiction and still asks the hardest questions about ambition and responsibility.'],
    [1661, ['To Sherlock Holmes she is always'], 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 1892, 307, 12.90, 4.3, 22, 1, 105,
     'Twelve cases, one violin, and the sharpest mind on Baker Street.',
     'From a king\'s blackmail problem to a red headed man paid to copy the encyclopaedia, these twelve stories show Sherlock Holmes at his best, told by his loyal friend Dr Watson. Short, clever and endlessly rereadable, this is the perfect first Holmes.'],
    [11, ['Alice was beginning to get very tired'], 'Alice\'s Adventures in Wonderland', 'Lewis Carroll', 1865, 128, 9.90, 4.0, 25, 0, 135,
     'Down the rabbit hole, where nothing makes sense and everything is curious.',
     'Bored on a riverbank, Alice follows a White Rabbit with a pocket watch and tumbles into Wonderland. There she grows and shrinks, argues with a caterpillar, attends a mad tea party and plays croquet with flamingos. Playful nonsense that readers of every age return to.'],
    [64317, ['In my younger and more vulnerable years'], 'The Great Gatsby', 'F. Scott Fitzgerald', 1925, 208, 12.50, 3.9, 15, 0, 165,
     'Green light, gold parties, and a man who believes he can repeat the past.',
     'Nick Carraway rents a small house on Long Island next door to the mysterious Jay Gatsby, whose parties are the talk of the summer of 1922. Gatsby wants one thing: Daisy Buchanan, Nick\'s cousin, who lives across the bay. A short, dazzling novel about longing, money and the American dream.'],
    [345, ['Left Munich at'], 'Dracula', 'Bram Stoker', 1897, 418, 12.90, 4.0, 0, 0, 175,
     'A solicitor travels to Transylvania to sell a house. His client has other plans.',
     'Jonathan Harker visits Count Dracula\'s castle to finalise a property sale and soon realises he is a prisoner. When the Count arrives in England, a small group led by Professor Van Helsing must stop him. Told through diaries, letters and newspaper clippings, it is still genuinely creepy.'],
];

// Member submissions waiting for approval (public domain, so they include real sample pages):
// [gid, markers, title, author, cat, year, pages, price, stock, added_by email, hook, synopsis]
$pending = [
    [45, ['Mrs. Rachel Lynde lived just where the Avonlea main road'], 'Anne of Green Gables', 'L. M. Montgomery', 'classics', 1908, 320, 10.90, 6, 'aisha@localhost',
     'They asked for a boy. They got Anne, with an e.',
     'Elderly siblings Matthew and Marilla Cuthbert send for an orphan boy to help on their farm on Prince Edward Island, and a talkative red haired girl arrives instead. Anne\'s imagination, mistakes and big heart slowly win over the whole town of Avonlea.'],
    [236, ['of a very warm evening in the Seeonee hills'], 'The Jungle Book', 'Rudyard Kipling', 'classics', 1894, 212, 9.90, 5, 'ben@localhost',
     'A boy raised by wolves, taught by a bear and a panther, hunted by a tiger.',
     'Mowgli is adopted by a wolf pack in the Indian jungle and taught its law by Baloo the bear and Bagheera the panther, while Shere Khan the tiger waits. The book also includes other animal tales, such as the brave mongoose Rikki-tikki-tavi.'],
];
